// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using customerseller.Models;

#nullable disable

namespace customerseller.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523081538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("customerseller.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("customerseller.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("customerseller.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdditionalImages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Rating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reviews")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sizes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "sa",
                            Category = "Shoes",
                            DisplayId = "AV-001",
                            ImageUrl = "sa.jfif",
                            Price = 1850m,
                            Title = "Multicolor Khussa"
                        },
                        new
                        {
                            Id = "sb",
                            Category = "Shoes",
                            DisplayId = "AV-002",
                            ImageUrl = "sb.jfif",
                            Price = 2200m,
                            Title = "Brown Winter Boots"
                        },
                        new
                        {
                            Id = "gs",
                            Category = "Shoes",
                            DisplayId = "AV-003",
                            ImageUrl = "gs.jpg",
                            Price = 1700m,
                            Title = "Nude Heels"
                        },
                        new
                        {
                            Id = "blue",
                            Category = "Shoes",
                            DisplayId = "AV-004",
                            ImageUrl = "blue.jpg",
                            Price = 1450m,
                            Title = "Brown Sandals"
                        },
                        new
                        {
                            Id = "boot",
                            Category = "Shoes",
                            DisplayId = "AV-005",
                            ImageUrl = "boot.jpg",
                            Price = 2100m,
                            Title = "Beige Block Heel Boots"
                        },
                        new
                        {
                            Id = "red",
                            Category = "Shoes",
                            DisplayId = "AV-006",
                            ImageUrl = "red.jpg",
                            Price = 1950m,
                            Title = "Maroon Heels"
                        },
                        new
                        {
                            Id = "mb",
                            Category = "Shoes",
                            DisplayId = "AV-007",
                            ImageUrl = "mb.jpg",
                            Price = 2650m,
                            Title = "Brown Mens Boots"
                        },
                        new
                        {
                            Id = "rr",
                            Category = "Shoes",
                            DisplayId = "AV-008",
                            ImageUrl = "rr.jpg",
                            Price = 1590m,
                            Title = "Burgundy Rain Boots"
                        },
                        new
                        {
                            Id = "gg",
                            Category = "Shoes",
                            DisplayId = "AV-009",
                            ImageUrl = "gg.jpg",
                            Price = 2490m,
                            Title = "Metallic Sneakers Set"
                        },
                        new
                        {
                            Id = "wd",
                            Category = "Shoes",
                            DisplayId = "AV-010",
                            ImageUrl = "wd.jpg",
                            Price = 1990m,
                            Title = "Formal Shoes (Men)"
                        },
                        new
                        {
                            Id = "bb",
                            Category = "Shoes",
                            DisplayId = "AV-012",
                            ImageUrl = "bb.jpg",
                            Price = 1850m,
                            Title = "Hat & Shoes Set"
                        },
                        new
                        {
                            Id = "bg",
                            Category = "Shoes",
                            DisplayId = "AV-013",
                            ImageUrl = "bg.jpg",
                            Price = 2350m,
                            Title = "Vintage Brown Boots"
                        },
                        new
                        {
                            Id = "bbb",
                            Category = "Bags",
                            DisplayId = "AV-040",
                            ImageUrl = "bbb.jpg",
                            Price = 1950m,
                            Title = "Sunny Sunflower Tote"
                        },
                        new
                        {
                            Id = "cc",
                            Category = "Bags",
                            DisplayId = "AV-041",
                            ImageUrl = "cc.jpg",
                            Price = 2250m,
                            Title = "Soft Knit Handbag"
                        },
                        new
                        {
                            Id = "dd",
                            Category = "Bags",
                            DisplayId = "AV-042",
                            ImageUrl = "dd.jpg",
                            Price = 1690m,
                            Title = "Brown Summer Tote"
                        },
                        new
                        {
                            Id = "ee",
                            Category = "Bags",
                            DisplayId = "AV-043",
                            ImageUrl = "ee.jpg",
                            Price = 2100m,
                            Title = "Pastel Woven Tote"
                        },
                        new
                        {
                            Id = "ggg",
                            Category = "Bags",
                            DisplayId = "AV-044",
                            ImageUrl = "ggg.jpg",
                            Price = 2750m,
                            Title = "Blush Knit Purse"
                        },
                        new
                        {
                            Id = "ff",
                            Category = "Bags",
                            DisplayId = "AV-045",
                            ImageUrl = "ff.jpg",
                            Price = 1890m,
                            Title = "Vivid Boho Crossbody"
                        },
                        new
                        {
                            Id = "hh",
                            Category = "Bags",
                            DisplayId = "AV-046",
                            ImageUrl = "hh.jpg",
                            Price = 2090m,
                            Title = "Classic Straw Tote"
                        },
                        new
                        {
                            Id = "ii",
                            Category = "Bags",
                            DisplayId = "AV-047",
                            ImageUrl = "ii.jpg",
                            Price = 2450m,
                            Title = "Sunset Chevron Bag"
                        },
                        new
                        {
                            Id = "jj",
                            Category = "Bags",
                            DisplayId = "AV-048",
                            ImageUrl = "jj.jpg",
                            Price = 2350m,
                            Title = "Emerald Chic Tote"
                        },
                        new
                        {
                            Id = "kk",
                            Category = "Bags",
                            DisplayId = "AV-049",
                            ImageUrl = "kk.jpg",
                            Price = 2150m,
                            Title = "Golden Lace Satchel"
                        },
                        new
                        {
                            Id = "ll",
                            Category = "Bags",
                            DisplayId = "AV-050",
                            ImageUrl = "ll.jpg",
                            Price = 1990m,
                            Title = "Lemon Chic Clutch"
                        },
                        new
                        {
                            Id = "tc",
                            Category = "Toys",
                            DisplayId = "AV-139",
                            ImageUrl = "tc.jpg",
                            Price = 1500m,
                            Title = "White Teddy Bear"
                        },
                        new
                        {
                            Id = "td",
                            Category = "Toys",
                            DisplayId = "AV-140",
                            ImageUrl = "td.jpg",
                            Price = 1800m,
                            Title = "Teddy Bear Couple"
                        },
                        new
                        {
                            Id = "tf",
                            Category = "Toys",
                            DisplayId = "AV-142",
                            ImageUrl = "tf.jpg",
                            Price = 1700m,
                            Title = "Brown Teddy Pair"
                        },
                        new
                        {
                            Id = "te",
                            Category = "Toys",
                            DisplayId = "AV-144",
                            ImageUrl = "te.jpg",
                            Price = 1400m,
                            Title = "Knitted Toy Trio"
                        },
                        new
                        {
                            Id = "bear",
                            Category = "Toys",
                            DisplayId = "AV-147",
                            ImageUrl = "bear.jfif",
                            Price = 1550m,
                            Title = "Blue Bear and Pink Pig Plush"
                        },
                        new
                        {
                            Id = "tom",
                            Category = "Toys",
                            DisplayId = "AV-148",
                            ImageUrl = "tom.jfif",
                            Price = 1750m,
                            Title = "Tom and Jerry Crochet Dolls"
                        },
                        new
                        {
                            Id = "nn",
                            Category = "Home",
                            DisplayId = "AV-154",
                            ImageUrl = "nn.jpg",
                            Price = 2850m,
                            Title = "Green Swirl Plates"
                        },
                        new
                        {
                            Id = "oo",
                            Category = "Home",
                            DisplayId = "AV-155",
                            ImageUrl = "oo.jpg",
                            Price = 2100m,
                            Title = "Rustic Spoon Bundle"
                        },
                        new
                        {
                            Id = "pp",
                            Category = "Home",
                            DisplayId = "AV-156",
                            ImageUrl = "pp.jpg",
                            Price = 1990m,
                            Title = "Wicker Tray Decor"
                        },
                        new
                        {
                            Id = "tt",
                            Category = "Home",
                            DisplayId = "AV-159",
                            ImageUrl = "tt.jpg",
                            Price = 2550m,
                            Title = "Artisan Brown Vase"
                        },
                        new
                        {
                            Id = "db",
                            Category = "HomeDecor",
                            DisplayId = "AV-164",
                            ImageUrl = "db.jfif",
                            Price = 1290m,
                            Title = "Daisy Candle Set"
                        },
                        new
                        {
                            Id = "dc",
                            Category = "HomeDecor",
                            DisplayId = "AV-165",
                            ImageUrl = "dc.jfif",
                            Price = 1190m,
                            Title = "Star Wall Hanging"
                        },
                        new
                        {
                            Id = "kb",
                            Category = "Kitchen",
                            DisplayId = "AV-175",
                            ImageUrl = "kb.jfif",
                            Price = 2190m,
                            Title = "Wooden Spiral Platter"
                        },
                        new
                        {
                            Id = "kc",
                            Category = "Kitchen",
                            DisplayId = "AV-176",
                            ImageUrl = "kc.jfif",
                            Price = 1890m,
                            Title = "Wooden Plate Rack Set"
                        });
                });

            modelBuilder.Entity("customerseller.Models.TrackingStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("TrackingSteps");
                });

            modelBuilder.Entity("customerseller.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("customerseller.Models.CartItem", b =>
                {
                    b.HasOne("customerseller.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("customerseller.Models.TrackingStep", b =>
                {
                    b.HasOne("customerseller.Models.Order", null)
                        .WithMany("TrackingTimeline")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("customerseller.Models.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("TrackingTimeline");
                });
#pragma warning restore 612, 618
        }
    }
}
